version: "3"

services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
  tests:
    build:
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    command: ["yarn", "test"]
